name: On pr

on:
  pull_request:


jobs:
  do-release-stuff:
    name: Do release stuff
    environment: on-pr
    runs-on: ubuntu-22.04
    steps:
      - name: echo secret
        run: echo ${{ secrets.DO_NOT_ECHO }}