name: On release

on:
  release:
    types: [published]


jobs:
  do-release-stuff-on-branch-protection:
    name: Branch protection
    environment: on-branch-protection
    runs-on: ubuntu-22.04
    steps:
      - name: echo secret
        run: echo ${{ secrets.DO_NOT_ECHO }}
  do-release-stuff-on-selected-branches:
    name: Selected branches
    environment: on-selected-branches
    runs-on: ubuntu-22.04
    steps:
      - name: echo secret
        run: echo ${{ secrets.DO_NOT_ECHO }}